server:
  port: 8080

# ** 系统自定义配置项内容 **
ltsystem:
  file:
    basePath: file/ # 文件存储的跟路径,绝对路径-直接使用,相对路径-项目运行目录下
  sysmsg:
    host: test.qdlimap.com
  swagger:
    serviceUrl: test.qdlimap.com/api/

logging:
  level:
    root: info
    org.litu: info
  freemarker.cache: error

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/normalappdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: litugaoke01
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: ltgk # Redis服务器连接密码（默认为空）
