server:
  port: 8081

# ** 系统自定义配置项内容 **
ltsystem:
  file:
    basePath: E:/0Temp/file/ # 文件存储的跟路径,绝对路径-直接使用,相对路径-项目运行目录下
  sysmsg:
    host: localhost:8081
  swagger:
    serviceUrl: localhost:8080/api/


logging:
  level:
    root: info
    org.litu: debug
  freemarker.cache: error
  # config: classpath:logback-dev.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/normalappdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: qazwsx123
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: litugaoke01! # Redis服务器连接密码（默认为空）