server:
  port: 8080

# ** 系统自定义配置项内容 **
ltsystem:
  file:
    basePath: E:/0Temp/file/ # 文件存储的跟路径,绝对路径-直接使用,相对路径-项目运行目录下
  sysmsg:
    host: 118.190.202.102:6033
  swagger:
    serviceUrl: 118.190.202.102:6033/api/

logging:
  level:
    root: info
    org.litu: info
  freemarker.cache: error

spring:
  datasource:
    url: jdbc:mysql://47.94.198.207:3306/normalappdb?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sa
    password: qazwsx123
  redis:
    database: 2  # Redis数据库索引（默认为0）
    host: 118.190.202.102 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: litugaoke01! # Redis服务器连接密码（默认为空）